# Enable debug mode (true/false)
debug: false

# The host the server binds to
host: "localhost"

# The port the server listens on
port: "8080"

# The public base URL of application, used for generating OAuth redirect URIs
base_url: "http://localhost:8080"

# Secret key used for signing tokens
secret: "your-secret-key"

# Oauth callback URL, Left it empty if you don't want to use oauth proxy, and it will callback to the orginal server
oauth_proxy_base_url: ""

# If you want to use oauth proxy, you need to set the secret here, and place the same secret in the oauth-proxy service
oauth_proxy_secret: ""

# PostgreSQL connection string
database_url: "postgres://user:password@localhost:5432/dbname?sslmode=disable"

# Path to database migration source
migration_source: "file://internal/database/migrations"

# Access token expiration duration (e.g. "15m", "1h")
access_token_expiration: "15m"

# Refresh token expiration duration (e.g. "720h" for 30 days)
refresh_token_expiration: "720h"

# URL of the OpenTelemetry collector (optional)
otel_collector_url: ""

# Google OAuth credentials
google_oauth:
  client_id: "your-google-oauth-client-id"
  client_secret: "your-google-oauth-client-secret"

# Gemini API key
gemini_api_key: "your-gemini-api-key"

# Error Log file path
err_log_path: "errorlogs/incident_0001_59e41abb.json"